### ISSUE TITLE
Bug in input longitude correction

### ISSUE THREAD

**Issue by ZPYin** [martin-rdz/ARLreader#1]
https://github.com/martin-rdz/ARLreader/blob/100182366e024fcaf1b56e685ddfe8ff8975877a/ARLreader/__init__.py#L282

I think here should be             
`coord = (coord[0], coord[1]+360)`

to change the range of longitude to (-180, 180)

**Comment by martin-rdz** [comment]
@ZPYin: Thanks for the suggestion. I've fixed the bug.
Please note that the range of longitude is converted from (-180,180) to (0, 360).
