### ISSUE TITLE
After reading the ARL data, could we change it and draw new trajectory?

### ISSUE THREAD

**Issue by chung9916** [martin-rdz/ARLreader#13]
Dear author,

I have some questions about the ARL reader. After reading the ARL data, could we change it and draw new trajectory?

And before running, should we install numpy first? and install the ARL reader? Looking forward to your reply! Thanks!

Best Regards,
Chung

**Comment by martin-rdz** [comment]
Hi Chung,

this library only allows to read in the raw data files, for example for investigation.
Calculation of trajectories is/will not be included.
